# Generated by Django 4.0.1 on 2022-01-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='debit',
        ),
    ]
