# Generated by Django 4.0.1 on 2022-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Liability', 'Liability'), ('Revenue', 'Revenue'), ('Asset', 'Asset')], default='Asset', max_length=25),
        ),
    ]
