# Generated by Django 4.0.1 on 2022-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_entry_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=25),
        ),
    ]
