# Generated by Django 4.0.1 on 2022-01-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='type',
        ),
        migrations.AddField(
            model_name='entry',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_acc', to='Main.account'),
        ),
        migrations.AddField(
            model_name='entry',
            name='debit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_acc', to='Main.account'),
        ),
        migrations.AddField(
            model_name='entry',
            name='details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
