# Generated by Django 4.0.1 on 2022-01-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Payable', 'Payable'), ('Expense', 'Expense'), ('Receivable', 'Receivable'), ('Asset', 'Asset'), ('Revenue', 'Revenue')], default='Asset', max_length=25),
        ),
    ]
