# Generated by Django 4.0.1 on 2022-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuuser',
            name='currency',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
