# Generated by Django 4.0.1 on 2022-01-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_accuuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='accuuser',
            name='profile',
            field=models.ImageField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
